version: '3'
services: 
  hadoop:
    build: .
    image: hadoop
    container_name: hadoop
    ports:
     - "9870:9870"
     - "8088:8088"
     - "9864:9864"
     - "9000:9090"
     - "4040:4040"
     - "8888:8888"
    networks: 
     - data-master-network

  #mysql_db:
  #  image: mysql:latest
  #  container_name: mysql_db
  #  ports:
  #      - "3306:3306"
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=root
  #    - MYSQL_DATABASE=datamaster
  #  #volumes:
  #  #  - ./mysql:/var/lib/mysql
  #  networks: 
  #    - data-master-network

networks: 
  data-master-network:
    driver: bridge